# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5729f6af5fb790729d386c3acbedcc84d7ed3ec298988624f557b20119053f964b311dffd640d121cad4b5b8778a0b658db47b3d3824e358785333a5d7439e7b

test:
  secret_key_base: 8580660a665cbc12d4da4b91e66a039447cf3532fbd4a830bba295cebf2e1a84e91289d175169ecbf646ba7ea01fc7c9b642e1e23fc34c0032351f60374ce114

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
